xpos314/xpos314.web/Controllers/CategoryTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryTryController : Controller
    {
        private readonly XPOS_314Context db;
        private readonly CategoryTryService categoryTryService;
        public CategoryTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.categoryTryService = new CategoryTryService(db);
        }

        //public CategoryTryService(XPOS_314Context _db)
        //{
        //    this.db = _db;
        //}
        public IActionResult Index()
        {
            List<VMTblCategory> dataView = categoryTryService.GetAllData();
            return View(dataView);
        }

        public IActionResult Create()
        {
            VMTblCategory dataView = new VMTblCategory();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryService.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblCategory dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = categoryTryService.Edit(dataView);

                if (respon.Success)
                {
                    return View(respon.Entity);
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        public IActionResult Delete(int id)
        {
            VMTblCategory dataView = categoryTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblCategory dataView)
        {
            VMResponse respon = categoryTryService.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return View(respon.Entity);
        }



    }
}

xpos314/xpos314.web/Controllers/VariantTryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class VariantTryController : Controller
    {

        private readonly XPOS_314Context db;
        private readonly VariantTryService variantTryService;
        private readonly CategoryTryService categoryTryService;

        private static VMPage page = new VMPage();

        public VariantTryController(XPOS_314Context _db)
        {
            this.db = _db;
            this.variantTryService = new VariantTryService(db);
            this.categoryTryService = new CategoryTryService(db);
        }

        public IActionResult Index(VMPage pg)
        {
            ViewBag.idSort = string.IsNullOrEmpty(pg.sortOrder) ? "id_desc" : "";
            ViewBag.nameSort = pg.sortOrder == "name" ? "name_desc" : "name";
            ViewBag.currentSort = pg.sortOrder;
            ViewBag.currentShowData = pg.showData;

            if(pg.searchString != null)
            {
                pg.pageNumber = 1;
            }
            else
            {
                pg.searchString = pg.currentFilter;
            }

            ViewBag.currentFilter = pg.searchString;

            List<VMTblVariant> dataView = variantTryService.GetAllData();

            if (!string.IsNullOrEmpty(pg.searchString))
            {
                dataView = dataView.Where(a => a.NameVariant.ToLower().Contains(pg.searchString.ToLower())
                || a.NameCategory.ToLower().Contains(pg.searchString.ToLower())).ToList();                               
            }

            switch (pg.sortOrder)
            {
                case "name_desc":
                    dataView = dataView.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                case "name":
                    dataView = dataView.OrderBy(a => a.NameVariant).ToList();
                    break;
                case "id_desc":
                    dataView = dataView.OrderByDescending(a => a.Id).ToList();
                    break;
                default:
                    dataView = dataView.OrderBy(a => a.Id).ToList();
                    break;
            }

            int pageSize = pg.showData ?? 3;

            page = pg;

            return View(PaginatedList<VMTblVariant>.CreateAsync(dataView, pg.pageNumber ?? 1, pageSize));
        }


        public IActionResult Create()
        {
            VMTblVariant dataView = new VMTblVariant();
            ViewBag.DropdownCategory = categoryTryService.GetAllData();
            return View(dataView);
        }

        //coba submit

        [HttpPost]
        public IActionResult Create(VMTblVariant dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = variantTryService.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index", page);
                }
            }

            ViewBag.DropdownCategory = categoryTryService.GetAllData();
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            ViewBag.DropdownCategory = categoryTryService.GetAllData();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblVariant dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = variantTryService.Edit(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index", page);
                }
            }

            ViewBag.DropdownCategory = categoryTryService.GetAllData();
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail (int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            ViewBag.DropdownCategory = categoryTryService.GetAllData();
            return View(dataView);
        }

        public IActionResult Delete(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);            
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblVariant dataView)
        {
            VMResponse respon = variantTryService.Delete(dataView);

            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            return View(respon.Entity);
        }


    }
}

xpos314/xpos314.web/Views/CategoryTry/Create.cshtml
@using xpos314.viewmodels;
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "Create Category";
}

<div class="card">
    <div class="card-body">


        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post">
            @*<div class="mb-4 row">
                <label for="Id" class="col-sm-2 col-form-label">Id</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="Id" name="Id">
                </div>
            </div>*@
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-light" asp-controller="VariantTry" asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Delete.cshtml
@using xpos314.viewmodels;
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "Delete Category Try";
}

<div class="card">
    <div class="card-body">

        <form asp-action="Delete" method="post">
            <input type="hidden" name="Id" value="@Model.Id"/>

            <h3>Are you sure to delete @Model.NameCategory ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to List</a>
            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Detail.cshtml
@using xpos314.viewmodels;
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "Detail Category Try";
}

<div class="card">
    <div class="card-body">


        <div class="h4 mb-4">@ViewData["Title"]</div>

        @*<form asp-action="Detail" method="post">*@

            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                    @*<span asp-validation-for="NameCategory" class="text-danger"></span>*@
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>
            <div class="mb-4 row">
                <div class="col-sm-10">
                    @*<button type="submit" class="btn btn-primary">Submit</button>*@
                    <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to List</a>
                </div>
            </div>
        @*</form>*@
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Edit.cshtml
@using xpos314.viewmodels;
@model VMTblCategory
@{
    Layout = null;
    ViewData["Title"] = "Edit Category Try";
}

<div class="card">
    <div class="card-body">


        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-2 col-form-label">Name Category</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span asp-validation-for="NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>
            <div class="mb-4 row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="CategoryTry" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>
    </div>
</div>

xpos314/xpos314.web/Views/CategoryTry/Index.cshtml
@using xpos314.viewmodels;
@{
    ViewData["Title"] = "Category Try";
}

<div class="card">
    <div class="card-body">
        <h2 class="card-title">@ViewData["Title"]</h2>

        @*<div class="row">
            <form asp-action="Index" method="get" id="form_search">
                <div class="col-12">
                    <div class="customize-input float-right">
                        <div class="input-group">
                            <input type="text" class="form-control" name="searchString" value="@ViewBag.currentFilter" placeholder="Search.."/>
                            <div class="input-group-prepend">
                                @*<div class="input-group-text" id="tbn_search">*@
                                    @*<i class="bi search"></i>*@
                                    @*<button type="button" class="btn btn-secondary"  id="btn_search">Search</button>*@                       
                                @*</div>*@
                            @*</div>
                        </div>
                    </div>
                </div>
            </form>
        </div>*@

        <button type="button" class="btn btn-primary" id="btn_create">Create</button>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name Category</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (VMTblCategory item in Model)
                {
                    <tr>
                        <th scope="row">@item.Id</th>
                        <td>@item.NameCategory</td>
                        <td>@item.Description</td>
                        <td>
                            <a class="btn btn-primary btn_edit" data-id="@item.Id">Edit</a>
                            <a class="btn btn-success btn_detail" data-id="@item.Id">Detail</a>
                            <a class="btn btn-danger btn_delete" data-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
    //$(document).ready(function(){
    //    $("#btn_create").click(function(){
    //        $("#body_modal").empty()
    //        $("#body_modal").load("/CategoryTry/Create")
    //        $("#myModal").modal("show")
    //    })
    //})
    $(document).ready(function () {
        $("#btn_create").click(function () {
            $(".modal-body").empty()
            $(".modal-body").load("/CategoryTry/Create")
            $(".modal").modal("show")
        })

        $(".btn_edit").click(function(){
            var id = $(this).data("id")
            $(".modal-body").empty()
            $(".modal-body").load("/CategoryTry/Edit?id=" + id)
            $(".modal").modal("show")
        })

        $(".btn_detail").click(function(){
            var id = $(this).data("id")
            $(".modal-body").empty()
            $(".modal-body").load("/CategoryTry/Detail?id=" + id)
            $(".modal").modal("show")
        })

        $(".btn_delete").click(function(){
            var id = $(this).data("id")
            $(".modal-body").empty()
            $(".modal-body").load("/CategoryTry/Delete?id=" + id)
            $(".modal").modal("show")
        })

        $("#btn_search").click(function(){
            //alert("oke")
            $("#form_search").submit()
        })
    })
</script>