xpos314/xpos314.web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class CategoryController : Controller
    {
        private CategoryService categoryService;
        //private IConfiguration configuration;
        private int IdUser = 1;
        
        //public CategoryController(IConfiguration _configuration)
        //public CategoryController(IConfiguration _configuration)
        //{
        //    this.configuration = _configuration;
        //    this.categoryService = new CategoryService(this.configuration); //konstraktornya harus diisi dengan parameter
        //}

        public CategoryController(CategoryService _categoryService)
        {
            //this.configuration = _configuration;
            //this.categoryService = new CategoryService(this.configuration); //konstraktornya harus diisi dengan parameter
            //this.variantService = new VariantService(this.configuration);
            this.categoryService = _categoryService;

        }

        public async Task<IActionResult> Index(string sortOrder, 
                                                string searchString, 
                                                string currentFilter, 
                                                int? pageNumber, 
                                                int? pageSize)
        
        
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<TblCategory> data = await categoryService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a=>a.NameCategory.ToLower().Contains(searchString.ToLower()) 
                    || a.Description.ToLower().Contains(searchString.ToLower())                   
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCategory).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCategory).ToList();
                    break;
            }

            return View(PaginatedList<TblCategory>.CreateAsync(data, pageNumber ??1, pageSize??3));
        }

        public IActionResult Create()
        {
            TblCategory data = new TblCategory();
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblCategory dataParam)
        {
            dataParam.CreatedBy = IdUser;
            VMResponse respon = await categoryService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new {dataRespon = respon});
            }

            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExist(string nameCategory)
        {
            bool isExist = await categoryService.CheckCategoryByName(nameCategory);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TblCategory dataParam)
        {
            dataParam.UpdateBy = IdUser;
            VMResponse respon = await categoryService.Edit(dataParam);

            if(respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            int createBy = IdUser;
            VMResponse respon = await categoryService.Delete(id, createBy);

            if(respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }

        //coba sendiri

        public async Task<IActionResult> Detail(int id)
        {
            TblCategory data = await categoryService.GetDataById(id);
            return PartialView(data);
        }
    }
}

xpos314/xpos314.web/Views/Category/Create.cshtml
@using xpos314.datamodels;
@model TblCategory
@{
    Layout = null;
    ViewData["Title"] = "Create Category";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Create" method="post" id="form_input">
            @*<div class="mb-4 row">
            <label for="Id" class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id">
            </div>
            </div>*@
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span id="validate_NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-light" asp-controller="Category" asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass:"text-danger",
        rules:{
            NameCategory:{
                required: true,
                minlength: 5,
            }           
        },
        messages:{
            NameCategory:{
                required: "Please fill Name Category",
                minlength: "The name must consist of at least 10 character",
            }
        },
        submitHandler: function(form){
            var dataForm = $(form).serialize()

            var nameCategory = $("#NameCategory").val()

            //ajax

            $.ajax({
                url : "/Category/CheckNameIsExist",
                type: "get",
                //method : "get" >>> sama dengan type
                data: { nameCategory: nameCategory },
                dataType: "json",
                success: function(respon){
                    if(respon){
                        $("#validate_NameCategory").text("Name Category is already exsist")
                        return true;
                    }
                    else{
                        fungsiSubmit(dataForm) //nama dataForm harus dari atas
                    }
                }
            })

        }
    })

    function fungsiSubmit(dataParam){ //nama dataParam bebas
        $.ajax({
            url: "/Category/Create", //dalam jquery boleh pakai petik satu atau dua
            data:dataParam,
            type:"post",
            dataType:"json",
            success: function(respon){ //input >> request, hasil >> respon
                var data = respon.dataRespon
                if(data.success){
                    $(".modal").modal("hide")
                    //toastr.success(data.message)
                    //window.location.reload()
                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function (){
                                window.location.reload()
                            }
                        }
                    )
                }
                else{
                    //Toast.fire({
                    //    icon:"Failed",
                    //    title:data.message
                    //})
                    toastr.error(data.message)
                }
            }
        })
    }
</script>

xpos314/xpos314.web/Views/Category/Delete.cshtml
@using xpos314.datamodels;
@model TblCategory
@{
    Layout = null;
    ViewData["Title"] = "Delete Category";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h3>Are you sure to delete @Model.NameCategory ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to List</a>
            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/Category/Detail.cshtml
@using xpos314.datamodels;
@model TblCategory
@{
    Layout = null;
    ViewData["Title"] = "Detail Category";
}

<div class="card">
    <div class="card-body">


        <div class="h4 mb-4">@ViewData["Title"]</div>

        @*<form asp-action="Detail" method="post">*@

        <div class="mb-4 row">
            <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                @*<span asp-validation-for="NameCategory" class="text-danger"></span>*@
            </div>
        </div>
        <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
            </div>
        </div>
        <div class="mb-4 row">
            <div class="col-sm-10">
                @*<button type="submit" class="btn btn-primary">Submit</button>*@
                <a class="btn btn-light" asp-controller="Category" asp-action="Index">Back to List</a>
            </div>
        </div>
        @*</form>*@
    </div>
</div>

xpos314/xpos314.web/Views/Category/Edit.cshtml
@using xpos314.datamodels;
@model TblCategory
@{
    Layout = null;
    ViewData["Title"] = "Edit Category";
}

<div class="card">
    <div class="card-body">


        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory">
                    <span id="validate_NameCategory" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-light" asp-controller="Category" asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameCategory: {
                required: true,
                minlength: 5,
            }
        },
        messages: {
            NameCategory: {
                required: "Please fill Name Category",
                minlength: "The name must consist of at least 5 character",
            }
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            var nameCategory = $("#NameCategory").val()

            //ajax

            $.ajax({
                url: "/Category/CheckNameIsExist",
                type: "get",
                //method : "get" >>> sama dengan type
                data: { nameCategory: nameCategory },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameCategory").text("Name Category is already exsist")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm) //nama dataForm harus dari atas
                    }
                }
            })
        }
    })

    function fungsiSubmit(dataParam) { //nama dataParam bebas
        $.ajax({
            url: "/Category/Edit", //dalam jquery boleh pakai petik satu atau dua
            data: dataParam,
            type: "post",
            dataType: "json",
            success: function (respon) { //input >> request, hasil >> respon
                var data = respon.dataRespon
                if (data.success) {
                    $(".modal").modal("hide")
                    //toastr.success(data.message)
                    //window.location.reload()
                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    //Toast.fire({
                    //    icon:"Failed",
                    //    title:data.message
                    //})
                    toastr.error(data.message)
                }
            }
        })
    }
</script>

xpos314/xpos314.web/Views/Category/Index.cshtml
@using xpos314.datamodels
@model xpos314.viewmodels.PaginatedList<TblCategory>
@{
    ViewData["Title"] = "Category";
}

@*<h3>Category</h3>*@


<div class="card">
    @*<div class="card-header">*@
        <div class="card-body">

            <h1 class="card-title">@ViewData["Title"]</h1>

    <div class="row mb-3">
        <div class="col-12">
            <div class="d-flex justify-content-between">

           
        <button id="btn_create" class="btn btn-primary">Create</button>
                    <button id="btn_toast" class="btn btn-primary">Toast</button>

        
                <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                    <div class="input-group w-100 @*input-group-sm*@" @*style="width: 150px;"*@>
                        <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control float-right" placeholder="Search..">

                        <div class="input-group-append">
                            <button type="submit" class="input-group-text" title="search">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                            <div class="input-group-append">
                            <a class="btn btn-default" asp-action="Index" title="reset">
                                <i class="fas fa-redo"></i>
                            </a>
                            @*</div>*@
                        </div>
                    </div>
                </form>

                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-hover mb-3">
                <thead>
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                                <i class="fas fa-sort"></i>
                                Name Category
                            </a>
                        </th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.NameCategory</td>
                                <td>@item.Description</td>

                                <td>
                                    <a class="btn btn-warning btn_detail" dataid="@item.Id">Detail</a>
                                    <a class="btn btn-success btn_edit" dataid="@item.Id">Edit</a>
                                    <a class="btn btn-danger btn_delete" dataid="@item.Id">Delete</a>
                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                <div class="col-2">
                    
                    <form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                        @*<div class="ml-2">entries from @Model.TotalData data</div>*@
                        <div class="ml-2">entries from @Model.TotalData data</div>
                        <input type="hidden" name="sortOrder" id="sort_change" value="" />
                    </form>
                </div>
                <div class="col-10">
                    @*Page @Model.PageIndex of @Model.TotalPages*@
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {

        $("#btn_toast").click(function(){
            toastr.success("BERHASIL")
        })

        $("#btn_create").click(function () {
            $("#modal_body").empty();
            $("#modal_body").load("/Category/Create")
            $("#exampleModal").modal("show");
        });

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $("#modal_body").empty();
            $("#modal_body").load("/Category/Detail?id=" + id)
            $("#exampleModal").modal("show");
        });

        $(".btn_edit").click(function () {

            var id = $(this).attr("dataid")
            $("#modal_body").empty();
            $("#modal_body").load("/Category/Edit?id=" + id)
            $("#exampleModal").modal("show");
        });

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $("#modal_body").empty();
            $("#modal_body").load("/Category/Delete?id=" + id)
            $("#exampleModal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })

    });
</script>