xpos314/xpos314.web/Controllers/VariantController.cs
using Microsoft.AspNetCore.Mvc;
using xpos314.datamodels;
using xpos314.viewmodels;
using xpos314.web.Services;

namespace xpos314.web.Controllers
{
    public class VariantController : Controller
    {

        private CategoryService categoryService;
        private VariantService variantService;
        //private IConfiguration configuration;
        private int IdUser = 1;

        //public VariantController(IConfiguration _configuration)
        public VariantController(CategoryService _categoryService,VariantService _variantService)
        {
            //this.configuration = _configuration;
            //this.categoryService = new CategoryService(this.configuration); //konstraktornya harus diisi dengan parameter
            //this.variantService = new VariantService(this.configuration);
            this.categoryService = _categoryService;
            this.variantService = _variantService;

        }

        public async Task<IActionResult> Index(string sortOrder,
                                                string searchString,
                                                string currentFilter,
                                                int? pageNumber,
                                                int? pageSize)


        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblVariant> data = await variantService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                    || a.Description.ToLower().Contains(searchString.ToLower())
                    || a.NameCategory.ToLower().Contains(searchString.ToLower())
                    
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameVariant).ToList();
                    break;
            }

            return View(PaginatedList<VMTblVariant>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        ////coba nih

        //[HttpGet("GetDataByIdCategory/{id}")]
        //public <VMTblVariant> DataById(int id)
        //{
        //    TblCategory result = new TblCategory();
        //    result = db.TblCategories.Where(a => a.Id == id).FirstOrDefault()!;
        //    return result;
        //}

        public async Task<IActionResult> Create()
        {
            VMTblVariant data = new VMTblVariant();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        
        public async Task<IActionResult> Edit(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblVariant dataParam)
        {
            VMResponse respon = await variantService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await variantService.Delete(id);

            if (respon.Success)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index", id);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblVariant data = await variantService.GetDataById(id);
            return PartialView(data);
        }

    }
}

xpos314/xpos314.web/Views/Variant/Create.cshtml
@using xpos314.viewmodels;
@model VMTblVariant
@{
    Layout = null;
    ViewData["Title"] = "Create Variant";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Create" method="post" id="form_input">
            @*<div class="mb-4 row">
            <label for="Id" class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id">
            </div>
            </div>*@
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">             
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"), //collection, id(value), name(text) (yang ditampilkan)
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 5,
            },
            IdCategory : "required",
        },
        messages: {
            NameVariant: {
                required: "Please fill Name Variant",
                minlength: "The name must consist of at least 5 character",
            },
            IdCategory : "Please select category",
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            //ajax
            $.ajax({
                url: "/Variant/Create", //dalam jquery boleh pakai petik satu atau dua
                data: dataForm,
                type: "post",
                dataType: "json",
                success: function (respon) { //input >> request, hasil >> respon
                    var data = respon.dataRespon
                    if (data.success) {
                        $(".modal").modal("hide")
                        //toastr.success(data.message)
                        //window.location.reload()
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.error(data.message)
                    }
                }
            })
 
        }
    })
</script>

xpos314/xpos314.web/Views/Variant/Delete.cshtml
@using xpos314.viewmodels;
@model VMTblVariant
@{
    Layout = null;
    ViewData["Title"] = "Delete Variant";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post">
            <input type="hidden" name="Id" value="@Model.Id" />

            <h3>Are you sure to delete @Model.NameVariant ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-action="Index" class="btn btn-light">Back to List</a>
            </div>
        </form>

    </div>
</div>

xpos314/xpos314.web/Views/Variant/Detail.cshtml
@using xpos314.viewmodels;
@model VMTblVariant
@{
    Layout = null;
    ViewData["Title"] = "Detail Variant";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>

        <div class="mb-4 row">
            <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
            </div>
        </div>

        <div class="mb-4 row">
            <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
            </div>
        </div>

        <div class="mb-4 row">
            <label for="Description" class="col-sm-4 col-form-label">Description</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
            </div>
        </div>

        <div class="mb-4 row">
            <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

xpos314/xpos314.web/Views/Variant/Edit.cshtml
@using xpos314.viewmodels;
@model VMTblVariant
@{
    Layout = null;
    ViewData["Title"] = "Edit Variant";
}

<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" id="Id" name="Id" value="@Model.Id"/>
            @*<div class="mb-4 row">
            <label for="Id" class="col-sm-2 col-form-label">Id</label>
            <div class="col-sm-10">
            <input type="text" class="form-control" id="Id" name="Id">
            </div>
            </div>*@
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"), //collection, id(value), name(text) (yang ditampilkan)
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a class="btn btn-light" asp-controller="Variant" asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 5,
            },
            IdCategory: "required",
        },
        messages: {
            NameVariant: {
                required: "Please fill Name Variant",
                minlength: "The name must consist of at least 5 character",
            },
            IdCategory: "Please select category",
        },
        submitHandler: function (form) {
            var dataForm = $(form).serialize()

            //ajax
            $.ajax({
                url: "/Variant/Edit", //dalam jquery boleh pakai petik satu atau dua
                data: dataForm,
                type: "post",
                dataType: "json",
                success: function (respon) { //input >> request, hasil >> respon
                    var data = respon.dataRespon
                    if (data.success) {
                        $(".modal").modal("hide")
                        //toastr.success(data.message)
                        //window.location.reload()
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.error(data.message)
                    }
                }
            })

        }
    })
</script>

xpos314/xpos314.web/Views/Variant/Index.cshtml
@using System.Globalization;
@using xpos314.datamodels
@using xpos314.viewmodels
@model xpos314.viewmodels.PaginatedList<VMTblVariant>

@{
    ViewData["Title"] = "Variant";
}


<div class="card">
    @*<div class="card-header">*@
    <div class="card-body">

        <h1 class="card-title">@ViewData["Title"]</h1>

        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">


                    <button id="btn_create" class="btn btn-primary">Create</button>


                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100 @*input-group-sm*@" @*style="width: 150px;"*@>
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control float-right" placeholder="Search..">

                            <div class="input-group-append">
                                <button type="submit" class="input-group-text" title="search">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                            <div class="input-group-append">
                                <a class="btn btn-default" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                                @*</div>*@
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-hover mb-3">
                <thead>
                    <tr>
                        <th>
                            <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort">
                                <i class="fas fa-sort"></i>
                                Name Variant
                            </a>
                        </th>
                        <th>Name Category</th>
                        <th>Description</th>
                        <th>IsDelete</th>
                        <th>CreateDate</th>
                        <th>Action</th>
                        
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Count != 0)
                    {
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.NameVariant</td>
                                <td>@item.NameCategory</td>
                                <td>@item.Description</td>
                                <td>
                                    @if (@item.IsDelete == true)
                                    {
                                        <input type="checkbox" checked disabled/>
                                    }
                                    else
                                    {
                                        <input type="checkbox" disabled/>
                                    }
                                </td>
                                <td>@item.CreateDate.ToString("dddd, dd MMMM yyyy HH:mm:ss", new CultureInfo("id-ID"))</td>

                                <td>
                                    <a class="btn btn-warning btn_detail" dataid="@item.Id">Detail</a>
                                    <a class="btn btn-success btn_edit" dataid="@item.Id">Edit</a>
                                    <a class="btn btn-danger btn_delete" dataid="@item.Id">Delete</a>
                                </td>

                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="3">
                                <i>Data not found</i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            }
            <div class="row">
                <div class="col-2">

                    <form asp-action="Index" id="form_pagesize">
                        <select name="PageSize" id="PageSize"
                                class="form-control">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                        @*<div class="ml-2">entries from @Model.TotalData data</div>*@
                        <div class="ml-2">entries from @Model.TotalData data</div>
                        <input type="hidden" name="sortOrder" id="sort_change" value="" />
                    </form>
                </div>
                <div class="col-10">
                    @*Page @Model.PageIndex of @Model.TotalPages*@
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @nextDisabled">
                        Next
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewBag.CurrentSort"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewBag.CurrentFilter"
                       asp-route-pageSize="@ViewBag.CurrentPageSize"
                       class="btn btn-info float-right @prevDisabled">
                        Previous
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function () {

        $("#btn_create").click(function () {
            $(".modal-body").empty();
            $(".modal-body").load("/Variant/Create")
            $(".modal").modal("show");
        });

        $(".btn_detail").click(function () {

            var id = $(this).attr("dataid")
            $(".modal-body").empty();
            $(".modal-body").load("/Variant/Detail?id=" + id)
            $(".modal").modal("show");
        });

        $(".btn_edit").click(function () {

            var id = $(this).attr("dataid")
            $(".modal-body").empty();
            $(".modal-body").load("/Variant/Edit?id=" + id)
            $(".modal").modal("show");
        });

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid");
            $(".modal-body").empty();
            $(".modal-body").load("/Variant/Delete?id=" + id)
            $(".modal").modal("show");
        });

        $("#PageSize").val(@ViewBag.CurrentPageSize)

        $("#PageSize").change(function () {
            $("#form_pagesize").submit();
        })

    });
</script>